model:
  target: models.Model
  params:
    domain_dim: 768
    max_domain_num: 20
    seq_emb_dim: 1280
    contrastive_loss: True

optimizer:
  target: torch.optim.SGD
  params:
    lr: 0.001
    weight_decay: 5e-4
    momentum: 0.9 
  loss_fn: torch.nn.BCELoss

scheduler:
  target: torch.optim.lr_scheduler.LambdaLR
  lr_milestones: 
    - 300
    - 400
  lr_gamma: 0.1

data:
  batch_size: 64
  workers: 8
  train_data:
    target: datasets.GODataset
    params:
      level: cc
      split: 'train'
  valid_data:
    target: datasets.GODataset
    params:
      level: cc
      split: 'valid'
  test_data:
    - target: datasets.GODataset
      params:
        level: cc
        split: 'test'
        percent: 30
    - target: datasets.GODataset
      params:
        level: cc
        split: 'test'
        percent: 40
    - target: datasets.GODataset
      params:
        level: cc
        split: 'test'
        percent: 50
    - target: datasets.GODataset
      params:
        level: cc
        split: 'test'
        percent: 70
    - target: datasets.GODataset
      params:
        level: cc
        split: 'test'
        percent: 95