model:
  target: models.Model
  params:
    domain_dim: 768
    max_domain_num: 13
    seq_emb_dim: 1280
    cdconv_param:
      geometric_radii:
        - 8.0
        - 12.0
        - 16.0
        - 20.0
      sequential_kernel_size: 11
      kernel_channels: 
        - 24
      channels:
        - 256
        - 512
        - 1024
        - 2048
      base_width: 64.0
      embedding_dim: 256

optimizer:
  target: torch.optim.SGD
  params:
    lr: 0.001
    weight_decay: 5e-4
    momentum: 0.9 

scheduler:
  target: torch.optim.lr_scheduler.LambdaLR
  lr_milestones: 
    - 100
    - 300
  lr_gamma: 0.1

data:
  batch_size: 8
  workers: 8
  train_data:
    target: datasets.FoldDataset
    params:
      split: 'training'
  valid_data:
    target: datasets.FoldDataset
    params:
      split: 'validation'
  test_data:
    - target: datasets.FoldDataset
      params:
        split: 'test_fold'
    - target: datasets.FoldDataset
      params:
        split: 'test_family'
    - target: datasets.FoldDataset
      params:
        split: 'test_superfamily'